#name: DevOps Pipeline - Full Stack Calculator
#
#on:
#  push:
#    branches:
#      - main
#  workflow_dispatch:
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '18.x'
#
#      - name: Build Angular Frontend
#        run: |
#          cd frontend
#          npm install
#          npm run build -- --configuration production
#
#      - name: Setup .NET Core
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: '9.0.x'
#
#      - name: Publish Basic and Advanced APIs
#        run: |
#          dotnet publish BasicCalculatorApi/BasicCalculatorApi.csproj --configuration Release --output ./publish/basic
#          dotnet publish AdvancedCalculatorApi/AdvancedCalculatorApi.csproj --configuration Release --output ./publish/advanced
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and Push Docker Images
#        run: |
#          docker build -t ghcr.io/yourname/frontend:latest ./frontend
#          docker build -t ghcr.io/yourname/basic-calculator-api:latest ./BasicCalculatorApi
#          docker build -t ghcr.io/yourname/advanced-calculator-api:latest ./AdvancedCalculatorApi
#          
#          docker push ghcr.io/yourname/frontend:latest
#          docker push ghcr.io/yourname/basic-calculator-api:latest
#          docker push ghcr.io/yourname/advanced-calculator-api:latest
#
#      - name: SSH into server and update
#        uses: appleboy/ssh-action@v1.2.1
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          script: |
#            docker pull ghcr.io/yourname/frontend:latest
#            docker pull ghcr.io/yourname/basic-calculator-api:latest
#            docker pull ghcr.io/yourname/advanced-calculator-api:latest
#
#            cd /your/docker-compose/folder
#            docker-compose down
#            docker-compose up -d
